spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    # see https://github.com/pgjdbc/pgjdbc/issues/265
    url: 'jdbc:postgresql://localhost:5432/app?stringtype=unspecified'
    username: 'app'
    password: 'app'